local _colors = {
  Purple = '#d8a0df',
  DarkBlue = '#569cd6',
  LightBlue = '#9cdcfe',
  Cyan = '#48c8af',
  Green = '#57a64a',
  LightGreen = '#b8d7a3',
  Yellow = '#dcdca9',
  LightOrange = '#d69d85',
  Red = '#ec5f67',
  Gray = '#808080',
  DarkGray = '#3e3e3e',
  context = '#606060',
  LightGray = '#c8c9c1',

  fg = '#D4D4D4',
  bg = '#14161b',
  dark = '#252525',
}

return {

  Purple = _colors.Purple,
  DarkBlue = _colors.DarkBlue,
  LightBlue = _colors.LightBlue,
  Cyan = _colors.Cyan,
  LightGreen = _colors.LightGreen,
  Yellow = _colors.Yellow,
  LightOrange = _colors.LightOrange,
  Red = _colors.Red,
  Gray = _colors.Gray,
  DarkGray = _colors.DarkGray,
  context = _colors.context,
  LightGray = _colors.LightGray,

  fg = _colors.fg,
  bg = _colors.bg,
  dark = _colors.dark,

  Accent = _colors.LightBlue,
  Documentation = '#9ec4e6', -- documentation comments
  Comment = _colors.Green,
  Type = _colors.Cyan,
  Function = _colors.Yellow,
  KeyWord = _colors.DarkBlue,
  Preprocessor = _colors.Gray,
  Reference = _colors.LightBlue,
  ReferenceImmutable = _colors.LightOrange,
  Syntax = _colors.fg,
  Value = _colors.LightGreen,
  FlowControl = _colors.Purple,
  --Syntax = White,
  PanelEdges = '#171a20',    -- lualine and tab borders
  CursorFG = '#515052',
  CursorBG = '#AEAFAD',

  Exception = _colors.Purple,
  Error = '#F44747',
  Warning = '#ff8800',
  Info = '#FFCC66',
  Hint = '#4FC1FF',

  popup_back = '#2D2D30',
  search_orange = '#613214',
  search_blue = '#5e81ac',
  gray = '#808080',
  dark_gray = '#3e3e3e',
  light_gray = '#c8c9c1',
  blue = '#569CD6',
  dark_blue = '#223E55',
  light_blue = '#9CDCFE',
  cyan = '#4EC9B0',
  green = '#6A9955',
  light_green = '#B5CEA8',
  red = '#F44747',
  light_red = '#D16969',
  orange = '#CE9178',
  yellow = '#DCDCAA',
  yellow_orange = '#D7BA7D',
  purple = '#C586C0',
  magenta = '#D16D9E',

  ui_blue = '#264F78',
  DiffAdd = _colors.Green,
  DiffChange = _colors.DarkBlue,
  DiffDelete = _colors.Red,
  DiffText = '#265478',
}
